import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Input } from '../components/Input'
import { useForm } from '../hooks'
import styles from '../sass/Home.module.scss'

const Home: NextPage = () => {
	return (
		<Head>
			<title>Byteshark</title>
			<meta name="description" content="Generated by create next app" />
			<link
				href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=VT323&display=swap"
				rel="stylesheet"
			/>
		</Head>
	)
}

export default Home
