import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Input } from '../components/Input'
import { useForm } from '../hooks'
import styles from '../sass/Home.module.scss'



const Home: NextPage = () => {


  return (
      <Head>
        <title>Byteshark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



  )
}

export default Home
