import type { NextPage } from 'next'
import Head from 'next/head'

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Byteshark Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main>
          <h1>Login Page</h1>
          <p>Tu Money by the Face con ByteCard La tarjeta que mordera el mercado y sera un E-XI-TA-ZO Preparense para lo que se viene! UwU</p>
          <input type="text" placeholder="Email" />
          <input type="password" placeholder="Password" />
          <input type="submit" value="login" />
        </main>
    </div>
  )
}

export default Login