import type { NextPage } from 'next'
import Head from 'next/head'
import { Input } from '../components/Input'
import { useFormContext } from '../context/useFormContext'
import { useForm } from '../hooks'
import { Navbar, Title, Text } from '../ui'



const Login: NextPage = () => {

  const { formData } = useFormContext()

  const onSubmit = (e: any) => {
    e.preventDefault()
    console.log(formData)
    
  }

  return (
    <div>
      <Head>
        <title>Byteshark Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <main className='login'>
          <div
            className='login-title'
          >
          <Title
            type='h1'
          >
            Tu Money by the Face con <span className='color-primary mono-font byte'>ByteCard</span>
          </Title>
          <Title
            type='h3'
          >
            La tarjeta que mordera el mercado y sera un E-XI-TA-ZO 
            Preparense para lo que se viene! <span className='color-primary mono-font uwu'>UwU</span>   
          </Title>
          </div>

          <form
            className='login-form'
            onSubmit={onSubmit}
          >
            <div>
              <Input
                type='text'
                value={formData.email}
                name='email'
                placeholder='Email'
              />
              <Input 
                type='text'
                value={formData.password}
                name='password'
                placeholder='password'
              />

            </div>

            <Input
              type='submit'
              value='Iniciar sesion'
            />
          </form>
          <figure className='login-image'>
            <img src="./mockup.png" alt="mockup" />
          </figure>
        </main>
    </div>
  )
}

export default Login