import type { NextPage } from 'next'
import Head from 'next/head'
import { useForm } from '../hooks'
import { Navbar } from '../ui'

const data = {
  email: '',
  password: '',
} 

const Login: NextPage = () => {

  const { formData, onChangeEvent } = useForm(data)

  console.log(formData);
  

  const onSubmit = (e: any) => {
    e.preventDefault()
    console.log({formData})
  }

  return (
    <div>
      <Head>
        <title>Byteshark Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <main>
          <h1>Login Page</h1>
          <p>Tu Money by the Face con ByteCard La tarjeta que mordera el mercado y sera un E-XI-TA-ZO Preparense para lo que se viene! UwU</p>
          <input type="text" placeholder="Email" value={formData.email} onChange={onChangeEvent} name={'email'}/>
          <input type="password" placeholder="Password" value={formData.password} onChange={onChangeEvent} name={'password'}/>
          <input type="submit" value="login" onClick={onSubmit}/>
        </main>
    </div>
  )
}

export default Login